[package]
name = "carbon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cid = "0.9.0"
did-key = "0.2.0"
webrtc-media = "0.5.0"
either = "1.8.0"

[workspace]